# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-18 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=25, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True)),
                ('aplica', models.BooleanField()),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Condominio')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CuentaContable')),
                ('tipo_movimiento', models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='main.TipoMovimiento')),
            ],
            options={
                'db_table': 'cuotas_condominios',
                'managed': True,
            },
        ),
    ]
